### ISSUE TITLE
User can register to the app

### ISSUE THREAD

**Issue by tan-at** [APUOPE-RE/Wiki#13]
### Description
As a user, I want be able to register to the app with my email and a password, so that I can start using the tool.

**Acceptance criteria**

- The form has fields for username, email and password.
- A register button is located below the form.
- If the username and email input by the user haven't already used to register an account before, user is created an account and redirected to user's home page.
- If the username or email have already been used to register an account before, give them an error message that the username or email already have a registered account. Message should also instruct the user to use the password reset function in the login page if they have forgotten their password.

### Specification

**Sign in form**
- [ ] Form has username, email and password fields.
- [ ] Form has a register button that submits the form for validation.
- [ ] Form checks that the password conforms to basic standards of a strong password.

Subtasks:

- [ ] APUOPE-RE/backend#5
- [ ] APUOPE-RE/backend#6
- [ ] APUOPE-RE/frontend#3
- [ ] APUOPE-RE/frontend#8

Wiki: https://github.com/APUOPE-RE/Wiki/wiki/FR-%E2%80%90-Log-in-&-Registration

**Comment by tan-at** [comment]
When a user registers to the app, there needs to be a functionality to determine whether to register them as a student or a teacher.

The roles come with access to different functionalities, so we need to clarify how we do this with the help of the customer.

**Comment by roosavihlman** [comment]
New wiki address: https://github.com/APUOPE-RE/Wiki/wiki/FR-%E2%80%90-Registration
