### ISSUE TITLE
STORY Log in -page

### ISSUE THREAD

**Issue by roosavihlman** [APUOPE-RE/Wiki#18]
**WIP**
Needs discussion if there could be added the list of sub tasks under existing user stories 

_Note: Under this user story, there is also created the basic skeleton for UI._

Sub tasks:

- [ ] APUOPE-RE/backend#3
- [ ] APUOPE-RE/frontend#2
- [ ] APUOPE-RE/backend#4 

Specification: [FR ‐ Log In & Sign Up](https://github.com/APUOPE-RE/Wiki/wiki/FR-%E2%80%90-Log-In-&-Sign-Up)
