### ISSUE TITLE
User can start a new conversation

### ISSUE THREAD

**Issue by tan-at** [APUOPE-RE/Wiki#27]
### Description
As a user, I want be able to start a conversation with the AI, so that I can learn based on the requirements engineering course material.

**Acceptance criteria**

- User can input a text prompt to the AI tool.
- The text input field has a submit button on its right side.
- Pressing enter takes the input and sends it to the AI tool, that then returns an answer based on the prompt. The answer can be, for example, a response to the prompt, or a response marking that the prompt is unsafe, if it breaks the AI's guardrails (by being a forbidden topic etc.).
- When an input is sent, it and the response are saved as a new conversation to the AI tool. The conversation should have a header created based on the first response, which is shown in the list of old conversations.

### Specification

**Conversation view**
- [ ] Chat has an input field for a text prompt.
- [ ] Chat has a submit button that submits the prompt to the AI tool.
- [ ] Prompt can also be submitted by pressing the enter key.
- [ ] Chat has an output view that shows the conversation history.
- [ ] When a prompt has been submitted, it is added to the output view.
- [ ] When a response is received, it is added to the output view.

**TODO**
- Design the chat view.

One option is to make the view similar to ChatGPT's view:
![Image](https://github.com/user-attachments/assets/eede9b9a-7c67-4f66-95b7-87fd501e6dd7)

Subtasks:

- [ ] APUOPE-RE/frontend#13
- [ ] APUOPE-RE/backend#11
- [ ] APUOPE-RE/backend#13

**Comment by tan-at** [comment]
User story seems long-ish. Should some of it be shortened and moved to a separate user story?
