### ISSUE TITLE
User can view old conversations

### ISSUE THREAD

**Issue by tan-at** [APUOPE-RE/Wiki#28]
### Description
As a user, I want be able to view my old conversations with the AI, so that I can see what I have prompted the AI with.

**Acceptance criteria**

- User can view a list of the previous conversations they've had with the AI tool.
- The entries on the list should be grouped based on the time of the latest prompt in each conversation. (The last time the conversation was "active").
- The list should show headers of previous conversations.
- The user can click on a header to open the conversation and view individual prompts they've made and responses they've received from the AI tool.
- When a conversation is opened, its header on the conversation list should be highlighted so the user can easily see which conversation is shown on the screen.

### Specification

**Old conversations view**
- [ ] View has a list of the headers of old conversations with the AI tool.
- [ ] Clicking on a header opens the conversation, showing prompts to, and responses from the AI tool.
- [ ] When a conversation is opened, its header on the conversation list should be highlighted.

**TODO**
- Design the chat view.

One option is to make the view similar to ChatGPT's view:
![Image](https://github.com/user-attachments/assets/bd4fe5ed-8ef7-463d-b85f-e8be32fc59be)
