### ISSUE TITLE
User can continue an old conversation

### ISSUE THREAD

**Issue by tan-at** [APUOPE-RE/Wiki#29]
### Description
As a user, I want be able to continue my old conversations with the AI, so that I can continue on a topic I have previously prompted the AI tool with.

**Acceptance criteria**

- User can continue a previous conversation they've had with the AI tool.
- When the user has opened a previous conversation, they should be shown the conversation history, including their prompts and the responses from the AI tool.
- When the user submits a prompt, it is added to the conversation output view.
- When the AI tool outputs it's response, it is added to the conversation output view.

### Specification

**Conversation view**
- [ ] Chat has an input field for a text prompt.
- [ ] Chat has a submit button that submits the prompt to the AI tool.
- [ ] Prompt can also be submitted by pressing the enter key.
- [ ] Chat has an output view that shows the conversation history.
- [ ] When a prompt has been submitted, it is added to the output view.
- [ ] When a response is received, it is added to the output view.

**TODO**
- Design the chat view.

One option is to make the view similar to ChatGPT's view:
![Image](https://github.com/user-attachments/assets/1b0465da-fa7c-4349-bcb3-3c106361a3a3)
