### ISSUE TITLE
User can delete an old conversation

### ISSUE THREAD

**Issue by tan-at** [APUOPE-RE/Wiki#30]
### Description
As a user, I want be able to delete my old conversations with the AI, so that I can remove it from my view.

**Acceptance criteria**

- User can delete a previous conversation they've had with the AI tool.
- When the user has chosen the option to delete a chosen conversation, the user is shown a window confirmation pop-up window asking if they are sure they want to delete the coversation.
- The confirmation window should have two buttons. One with the text "Delete", and a second with the text "Cancel".
- If the user clicks on the "Delete" button, the conversation is deleted, and the user is taken back to the list of old conversations.
- If the user clicks on the "Cancel" button, the conversation is not deleted, and the user is taken back to the list of old conversations.

### Specification

**Old conversation view**
- [ ] View has an option/button next to each header of old conversations that allows the user delete the old conversation.
- [ ] Clicking on a "Delete conversation" button shows the user a pop-up window with two buttons: One that deletes the button, and a second that cancels the deletion process.
- [ ] Delete button deletes the conversation, and the user is taken back to the list of old conversations.
- [ ] Cancel button cancels the deletion process, and the user is taken back to the list of old conversations.

**TODO**
- Design the chat view.

One option is to make the view similar to ChatGPT's view:
![Image](https://github.com/user-attachments/assets/c1d42c10-a808-436a-a140-eafb7c40fcf8)
