### ISSUE TITLE
User can do a customizable quiz

### ISSUE THREAD

**Issue by tan-at** [APUOPE-RE/Wiki#32]
### Description
As a user, I want be able to generate a customized quiz by the AI, so that I can choose what course parts I want to test my knowledge on.

**Acceptance criteria**

- User can create a customized quiz about the course topics with the AI.
- User can choose what topics they want to be quizzed on. Quiz topics can be chosen per chapter of the course material, e.g. Chapter 1. Introduction, Chapter 5. Working with the customer.*
- Quiz topics can also be chosen freeform with keywords or key sentences, e.g. "Prioritizing requirements and how to keep the customer in the loop of the requirements managing process" or "How to extract requirements from the customer".***
- User can choose if they want to have multiple-choice questions, open-ended questions, or both.
- User can choose how many questions they want generated.
- When the user submits their quiz settings to be made into a quiz, the settings should be stored, so the user can choose "previous quiz" as a template the next time they create a quiz.
- Questions in the quiz should either have a text field or checkboxes for answering depending on if the question is an open-ended or a multiple-choice question.
- When the user clicks a "finish quiz" button, they should prompted with a "are you sure you are finished" message to confirm that they want to exit the quiz.
- After a user has completed a quiz, the results of the quiz should be stored. **Date and time when quiz was completed**, **each question's topics**, **each question**, **user's answers to each question**, **the correct/model answer to each question**, **and how well the user scored to each question** should all be stored.
- After a user has completed a quiz and the results have been saved, the user should be shown the results of the quiz and feedback to each of the user's answers.

### Specification

**Quiz settings view**
- [ ] View has section for a list of the chapters the user can choose to be quizzed about. Section also has an option to input freeform keywords or key sentences to be quizzed about.
- [ ] View has a section for choosing multiple-choice questions, open-ended questions, or both.
- [ ] View has a section to set the number of questionsto be generated.
- [ ] View shows the user what quiz settings they have chosen.
- [ ] View has a button to reapply previous quiz's settings.
- [ ] View has a button for generating the quiz based on the chosen settings.
- [ ] When the quiz is generated, the settings are saved so they can be used to do generate a quiz with the same settings the next time.

**Quiz view**
- [ ] Each open-ended question in the quiz has a text field for answering.
- [ ] Each multiple-choice question in the quiz has checkboxes for answering.
- [ ] View has a "finish quiz" button. When pressed, user is prompted with a "are you sure you are finished" message to confirm that they want to exit the quiz.
- [ ] "Are you sure you are finished" message should have two buttons: One for finishing the quiz (Finish quiz), and one for going back to the quiz (Cancel).
- [ ] When a quiz is finished, the results of the quiz are stored. **Date and time when quiz was completed**, **each question's topics**, **each question**, **user's answers to each question**, **the correct/model answer to each question**, **and how well the user scored to each question** are all stored.
- [ ] When the quiz results have been saved, the user is shown the results of the quiz and feedback to each of the user's answers.
- [ ] Results of the quiz show the user the **Date and time when quiz was completed**, **each question's topics**, **each question**, **user's answers to each question**, **the correct/model answer to each question**, **and how well the user scored to each question**.
- [ ] The results view has a button, which closes the results and takes the user to the list of previous quiz results.

**TODO**
- Separate the monstrous-sized user story into two pieces? ;_;
- Design the quiz view.
- Design the quiz result view.
-> Use a similar side-bar for listing previous quiz-results as with Chat GPT showing previous discussions? Could help with usability, if the side-bar is similar as in the conversation view.
![Image](https://github.com/user-attachments/assets/9f501990-6fde-4df5-80c4-5bf0d9243bc1)

### Notes
*We do not know how the course material is structured. Can this affect how the AI "learns" from the course material, and how it constructs chapters? If the course material changes, can this make this way of customizing quiz topics invalid?

***This can be used to compensate the possible shortcomings of the chapter-based quiz topic choosing, as well as make the tool more flexible to use.
