### ISSUE TITLE
User can view the results of previous quizzes

### ISSUE THREAD

**Issue by tan-at** [APUOPE-RE/Wiki#33]
### Description
As a user, I want be able to view previous quiz results, so that I can track how I've learned the course objectives over time.

**Acceptance criteria**

- User can view a list of all previously done quizzes.
- When a user chooses a specific quiz, they are shown the **Date and time when quiz was completed**, **each question's topics**, **each question**, **user's answers to each question**, **the correct/model answer to each question**, **and how well the user scored to each question**.

### Specification

**Previously done quizzes view**
- [ ] View has a list of previously done quizzes' results.
- [ ] Clicking on a quiz-result on the list opens the specified quiz's results.
- [ ] Results of a quiz show the user the **Date and time when quiz was completed**, **each question's topics**, **each question**, **user's answers to each question**, **the correct/model answer to each question**, **and how well the user scored to each question**.
- [ ] When a quiz-result is opened, it should be highlighted on the quiz-results list.

**TODO**
- Design the quiz result view.
-> Use a similar side-bar for listing previous quiz-results as with Chat GPT showing previous discussions? Could help with usability, if the side-bar is similar as in the conversation view.
![Image](https://github.com/user-attachments/assets/07fd83fc-bd35-443f-a302-d80ff1c91a72)
