### ISSUE TITLE
User can view the combined results of all the quizzes they've done

### ISSUE THREAD

**Issue by tan-at** [APUOPE-RE/Wiki#34]
### Description
As a user, I want be able to view a combination of all of my quiz results, so that I can track how I've learned the course objectives over time.

**Acceptance criteria**

- User can view a combination of all of their quiz results.
- The view shows the user the combination of all of the quiz results they have done in the past. The results should show **Date and time when quiz was completed**, **each question's topics**, **each question**, **user's answers to each question**, **the correct/model answer to each question**, **and how well the user scored to each question**.
- User is shown charts of how their scores based on certain topics have changed over time.

### Specification

**Combination of quiz results view**
- [ ] View has a list of a combination of all of the user's quiz results
- [ ] Combined quiz-results show the user the **Date and time when quiz was completed**, **each question's topics**, **each question**, **user's answers to each question**, **the correct/model answer to each question**, **and how well the user scored to each question**.
- [ ] View includes charts of how user's scores based on certain topics have changed over time.

**TODO**
- Design the quiz result view.
-> Use a similar side-bar for listing previous quiz-results as with Chat GPT showing previous discussions? Could help with usability, if the side-bar is similar as in the conversation view.
![Image](https://github.com/user-attachments/assets/6f02e66b-f5d7-4486-b2bd-ae0fcc6a305e)
