### ISSUE TITLE
<TODO>Teacher can generate a quiz based on certain topics

### ISSUE THREAD

**Issue by ErickSch** [APUOPE-RE/Wiki#8]
### Description
As a teacher, I want to be able to select topics to generate a quiz about, so that I dont have to spend time developing te questions and options.

**Acceptance criteria**
- There's a list of topics about a certain subject.
- User can select one or more topics.
- There's a "generate quiz" button.
- When "generate quiz" button is clicked a quiz about the selected topics is generated.
- The generated quiz has questions and choices suggestion.

### Specification

**List of topics**
- [ ] The view shows a list of topics about a certain topic.
- [ ] User can select multiple topics at the same time.

**Quiz**
- [ ] "Generate quiz" button generates a quiz.
- [ ] Quiz is in an easy to understand format.
- [ ] Quiz shows questions and options for multiple choice.
