### ISSUE TITLE
Student can sign in using a sign in form

### ISSUE THREAD

**Issue by tan-at** [APUOPE-RE/Wiki#9]
### Description
As a student, I want be able to login with my credentials, so that I can start using the tool.

**Acceptance criteria**

- The form has fields for username and password.
- A sign in button is located below the form.
- If credentials are validated, user is authenticated and redirected to student's home page.

### Specification

**Sign in form**
- [ ] Form has username and password fields.
- [ ] Form has a sign in button that submits the form for validation.

- [ ] APUOPE-RE/backend#3
- [ ] APUOPE-RE/frontend#2
- [ ] APUOPE-RE/backend#4 
- [ ] APUOPE-RE/frontend#9

Wiki: https://github.com/APUOPE-RE/Wiki/wiki/FR-%E2%80%90-Log-in-&-Registration

**Comment by roosavihlman** [comment]
New wiki address: https://github.com/APUOPE-RE/Wiki/wiki/FR-%E2%80%90-Log-in
